name: Step 3

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_4_FILE: ".github/steps/4-step.md"

jobs:
  check_keywords:
    name: Check issue comment text for required keyword
    runs-on: ubuntu-latest
    steps:
      - name: Check for professortocat reference
        id: check_professortocat
        uses: skills/action-keyphrase-checker@v1
        with:
          text: ${{ github.event.comment.body }}
          keyphrase: "professortocat"
          case-sensitive: false
          minimum-occurrences: 1

  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.0

  load_config:
    needs: [find_exercise]
    name: Load Config File
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.load-config.outputs.result }}
    steps:
      - uses: actions/checkout@v4

      - name: Load YAML config with yq
        id: load-config
        uses: mikefarah/yq@master
        with:
          cmd: yq eval -o=json './ado/config.yml'

  post_next_step_content:
    name: Post next step content
    needs: [find_exercise, check_keywords, load_config]
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.7.0

      - name: Create comment - step finished
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          vars: |
            next_step_number: 4

      - name: Create comment - add step content
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_4_FILE }}
          vars: |
            ado_url: ${{ fromJson(needs.load_config.outputs.config).ado_url }}
            ado_project_name: ${{ fromJson(needs.load_config.outputs.config).ado_project_name }}
            ado_repository_name: ${{ fromJson(needs.load_config.outputs.config).ado_repository_name }}
            github_org: ${{ fromJson(needs.load_config.outputs.config).github_org }}
            target_github_repo_name: ${{ fromJson(needs.load_config.outputs.config).target_github_repo_name }}

      - name: Create comment - watching for progress
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "Step 4"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
